# Generated by Django 4.0 on 2022-12-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store01', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='product01',
            name='หน่วย',
        ),
        migrations.AddField(
            model_name='product01',
            name='unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='หน่วยของสินค้า(ถุง/กล่อง/ชิ้น/ฯลฯ)'),
        ),
        migrations.AlterField(
            model_name='category01',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อประเภทสินค้า'),
        ),
        migrations.AlterField(
            model_name='category01',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ชื่อประเภทสินค้าภาษาอังกฤษ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='บ้านเลขที่ที่อยู่จัดส่ง'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='ที่อยู่จัดส่ง'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ได้รับคำสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=250, verbose_name='อีเมลลูกค้า'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อลูกค้า'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=255, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาสินค้าทั้งหมด'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่ได้รับคำสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store01.order', verbose_name='คำสั่งซื้อ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อชิ้น'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.CharField(max_length=250, verbose_name='สินค้า'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='จำนวน'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='available',
            field=models.BooleanField(default=True, verbose_name='สินค้าพร้อมขายหรือไม่'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store01.category01', verbose_name='ประเภทสินค้า'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างข้อมูลสินค้า'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียดสินค้า'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='image',
            field=models.ImageField(blank=True, upload_to='product', verbose_name='ภาพสินค้า'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='ชื่อสินค้าภาษาอังกฤษ'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='stock',
            field=models.IntegerField(verbose_name='จำนวนสินค้าที่พร้อมขาย'),
        ),
        migrations.AlterField(
            model_name='product01',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขข้อมูลสินค้า'),
        ),
    ]
