# Generated by Django 4.0 on 2022-12-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store01', '0005_banktransfer_remove_product01_หน่วย_product01_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า')),
                ('address', models.CharField(max_length=255, verbose_name='บ้านเลขที่ที่อยู่จัดส่ง')),
                ('city', models.CharField(max_length=255, verbose_name='ที่อยู่จัดส่ง')),
                ('postcode', models.CharField(max_length=10, verbose_name='รหัสไปรษณีย์')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมลลูกค้า')),
                ('money_transfer_slip', models.ImageField(upload_to='bank_transfer_slips/', verbose_name='สลิปโอนเงิน')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store01.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'ใบสั่งซื้อพร้อมสลิปโอนเงิน',
                'verbose_name_plural': 'ใบสั่งซื้อพร้อมสลิปโอนเงิน',
            },
        ),
    ]
